runtime: python39  

entrypoint: gunicorn -b :$PORT app:app --timeout 120  

# Configurações para servir arquivos estáticos
handlers:
  - url: /static
    static_dir: static  

  - url: /.*
    script: auto
    
vpc_access_connector:
  name: projects/gerenciador-tarefas-438612/locations/us-central1/connectors/conector

# Variáveis de ambiente para MySQL e Redis
env_variables:
  MYSQL_USER: "root"  
  MYSQL_PASSWORD: "Di021"  
  MYSQL_DB: "gerenciador_tarefas"  # Nome do banco de dados no MySQL
  INSTANCE_CONNECTION_NAME: "gerenciador-tarefas-438612:us-central1:mysql-instance-us-central"
  REDIS_HOST: "10.138.248.11"  # Endereço IP da instância do Redis
  REDIS_PORT: "6379"
  JWT_SECRET_KEY: "sua_chave_secreta_jwt"  # Defina uma chave secreta para o JWT

beta_settings:
  cloud_sql_instances: "gerenciador-tarefas-438612:us-central1:mysql-instance-us-central"
